#!/usr/bin/env bash

# env checks
if [ -z "$XDG_CONFIG_HOME" ]; then
    echo "no xdg config hom"
    echo "using ~/.config"
    XDG_CONFIG_HOME=$HOME/.config
fi

if [ -z "$DEV_ENV" ]; then
    echo "env var DEV_ENV needs to be present"
    exit 1
fi

# flags
dry_run="0"
warn_only="0"

if [[ $1 == "--dry" ]]; then
    dry_run="1"
fi

if [[ $1 == "--warn" ]]; then
    warn_only="1"
fi

# shared helpers
source "$DEV_ENV/lib/log.sh"
source "$DEV_ENV/lib/detect_os_and_run"

# functions
update_files() {
    if [[ $warn_only == "1" ]]; then
        return
    fi
    log "copying over files from: $1"
    pushd $1 &> /dev/null
    (
        configs=`find . -mindepth 1 -maxdepth 1 -type d`
        for c in $configs; do
            directory=${2%/}/${c#./}
            log "    removing: rm -rf $directory"

            if [[ $dry_run == "0" ]]; then
                rm -rf $directory
            fi

            log "    copying env: cp $c $2"
            if [[ $dry_run == "0" ]]; then
                cp -r ./$c $2
            fi
        done

    )
    popd &> /dev/null
}

copy() {
    if [[ $warn_only == "1" ]]; then
        warn_size "$1" "$2"
        return
    fi
    log "removing: $2"
    if [[ $dry_run == "1" ]]; then
        warn_size "$1" "$2"
    fi
    if [[ $dry_run == "0" ]]; then
        rm $2
    fi
    log "copying: $1 to $2"
    if [[ $dry_run == "0" ]]; then
        cp $1 $2
    fi
}

link() {
    log "symlinking: $1 -> $2"
    if [[ $warn_only == "1" ]]; then
        return
    fi
    if [[ $dry_run == "0" ]]; then
        ln -sf "$1" "$2"
    fi
}

mac() {
  link $DEV_ENV/env/.cl-mac-commands $HOME/.cl-commands
}
fedora() {
  link $DEV_ENV/env/.cl-fed-commands $HOME/.cl-commands
}
debian() {
  link $DEV_ENV/env/.cl-deb-commands $HOME/.cl-commands
}
fallback() {
    echo "OS not supported. Exiting."
    exit 1
}

# execution
log "env: $DEV_ENV"

update_files $DEV_ENV/env/.config $XDG_CONFIG_HOME
update_files $DEV_ENV/env/.local $HOME/.local

copy $DEV_ENV/env/.zsh_profile $HOME/.zsh_profile
copy $DEV_ENV/env/.zshrc $HOME/.zshrc
copy $DEV_ENV/env/.vimrc $HOME/.vimrc
copy $DEV_ENV/env/.gitconfig $HOME/.gitconfig
copy $DEV_ENV/env/.tmux.conf $HOME/.tmux.conf

copy $DEV_ENV/dev-env $HOME/.local/scripts/dev-env
copy $DEV_ENV/cl $HOME/.local/scripts/cl

detect_os_and_run \
  --mac-func mac \
  --fedora-func fedora \
  --debian-func debian \
  --fallback-func fallback
