#!/usr/bin/env bash

window_mode=${TMUX_PROJECT_WINDOW:-false}

switch_to() {
    if [[ -z $TMUX ]]; then
        tmux attach-session -t $1
    else
        tmux switch-client -t $1
    fi
}

has_session() {
    tmux list-sessions | grep -q "^$1:"
}

hydrate() {
    if [ -f $2/.tmux-sessionizer ]; then
        tmux send-keys -t $1 "source $2/.tmux-sessionizer" c-M
    elif [ -f $HOME/scripts/.tmux-sessionizer ]; then
        tmux send-keys -t $1 "source $HOME/scripts/.tmux-sessionizer" c-M
    fi
}

if [[ $# -eq 1 ]]; then
    selected=$1
else
  selected=$(\
        { find ~/github/personal ~/github ~/github/playground ~/github/learn ~/github/work ~/github/tools -mindepth 1 -maxdepth 1 -type d; echo ~/.dotfiles; echo ~/nvim; echo ~/.obsidian-settings; echo ~/.pi; echo ~/.agent; echo ~/.agents;} \
        | fzf)
fi


if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)

if $window_mode; then
    tmux rename-window -t "$TMUX_PANE" "$(basename "$selected")"
    cd "$selected" || exit 1

    if [[ -f .tmux-sessionizer ]]; then
        exec /bin/zsh -ic 'source "$1"; exec /bin/zsh -l' zsh "$PWD/.tmux-sessionizer"
    elif [[ -f $HOME/scripts/.tmux-sessionizer ]]; then
        exec /bin/zsh -ic 'source "$1"; exec /bin/zsh -l' zsh "$HOME/scripts/.tmux-sessionizer"
    else
        exec /bin/zsh -l
    fi
fi

tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -c $selected
    hydrate $selected_name $selected
    exit 0
fi

if ! has_session $selected_name; then
    tmux new-session -ds $selected_name -c $selected
    hydrate $selected_name $selected
fi

switch_to $selected_name
