#!/usr/bin/env bash

window_mode=false
selected=

case "$1" in
    --window|--replace)
        window_mode=true
        shift
        ;;
    --session)
        shift
        ;;
    "")
        ;;
    *)
        if [[ $# -eq 1 ]]; then
            selected=$1
        else
            printf 'Usage: tmux-sessionizer [mode] [directory]\n' >&2
            exit 2
        fi
        ;;
esac

switch_to() {
    if [[ -z $TMUX ]]; then
        tmux attach-session -t $1
    else
        tmux switch-client -t $1
    fi
}

has_session() {
    tmux list-sessions | grep -q "^$1:"
}

hydrate() {
    if [ -f $2/.tmux-sessionizer ]; then
        tmux send-keys -t $1 "source $2/.tmux-sessionizer" c-M
    elif [ -f $HOME/scripts/.tmux-sessionizer ]; then
        tmux send-keys -t $1 "source $HOME/scripts/.tmux-sessionizer" c-M
    fi
}

if [[ -z $selected ]]; then
  selected=$(\
        { find ~/github/personal ~/github ~/github/playground ~/github/learn ~/github/work ~/github/tools -mindepth 1 -maxdepth 1 -type d; echo ~/.dotfiles; echo ~/nvim; echo ~/.obsidian-settings; echo ~/.pi; echo ~/.agent; echo ~/.agents;
          [ -f ~/.tmux-contexts ] && cat ~/.tmux-contexts; } \
        | awk '!seen[$0]++' \
        | fzf)
fi


if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)

if $window_mode; then
    pane_target=${TMUX_PANE:-$(tmux display-message -p '#{pane_id}')}
    tmux rename-window -t "$pane_target" "$(basename "$selected")"
    cd "$selected" || exit 1

    if [[ -f .tmux-sessionizer ]]; then
        exec /bin/zsh -ic 'source "$1"; exec /bin/zsh -l' zsh "$PWD/.tmux-sessionizer"
    elif [[ -f $HOME/scripts/.tmux-sessionizer ]]; then
        exec /bin/zsh -ic 'source "$1"; exec /bin/zsh -l' zsh "$HOME/scripts/.tmux-sessionizer"
    else
        exec /bin/zsh -l
    fi
fi

tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -c $selected
    hydrate $selected_name $selected
    exit 0
fi

if ! has_session $selected_name; then
    tmux new-session -ds $selected_name -c $selected
    hydrate $selected_name $selected
fi

switch_to $selected_name
