#!/usr/bin/env bash

sudo apt -y update
sudo apt -y install git gh git-delta ripgrep xclip tldr shutter tmux lazygit

sudo git clone git@github.com:junegunn/fzf.git $HOME/personal/fzf
bash $HOME/personal/fzf/install
