#!/usr/bin/env bash
# add this file to ~/.local/scripts

# add this to .bashrc or .zhrc
# bindkey -s ^f "tmux-sessionizer\n"

if [[ $# -eq 1 ]]; then
    selected=$1
else
     selected=$(find ~/github/vim_/ ~/github/personal/ ~/github/  -mindepth 1 -maxdepth 1 -type d | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -c $selected
    exit 0
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c $selected
fi

tmux switch-client -t $selected_name


